import assert from 'node:assert/strict';
import {rankStandings} from '../src/standings.js';
import {simulatePlayoffs} from '../src/playoffs.js';
import {playProbability,availableThisWeek} from '../src/model/availability.js';
import {simulateLeague} from '../src/simulator.js';
import {buildNFLGameIndex,playerGameContext,validateNFLGames} from '../src/model/nfl-games.js';
import {createCorrelationContext} from '../src/model/correlation.js';
const teams=[{id:'A',name:'A',lineup:[{projection:20,position:'QB'}]},{id:'B',name:'B',lineup:[{projection:10,position:'QB'}]}],state={A:{wins:5,losses:3,points:700},B:{wins:5,losses:3,points:650}};
assert.equal(rankStandings(teams,state)[0].id,'A');assert.equal(playProbability({status:'OUT'}),0);assert.equal(playProbability({status:'ACTIVE'}),1);assert.equal(availableThisWeek({status:'ACTIVE',byeWeek:9},9,()=>0),false);
const postseason=simulatePlayoffs({qualifiers:teams,weeks:[15],rng:()=>.5,simulateTeamScore:t=>t.id==='A'?100:90});assert.equal(postseason.champion.id,'A');
const league={teams:teams.map((t,i)=>({...t,wins:i?0:1,losses:i?1:0,points:0})),schedule:[],playoffSpots:1},r1=simulateLeague({...league,simulations:50,seed:77,playoffWeeks:[15]}),r2=simulateLeague({...league,simulations:50,seed:77,playoffWeeks:[15]});assert.deepEqual(r1,r2);assert.equal(r1.find(x=>x.id==='A').playoffProbability,1);
const games=[{week:8,homeTeam:'NE',awayTeam:'NYJ'}];assert.equal(validateNFLGames(games).valid,true);const idx=buildNFLGameIndex(games),ne=playerGameContext({nflTeam:'NE'},8,idx),nyj=playerGameContext({nflTeam:'NYJ'},8,idx);assert.equal(ne.gameId,nyj.gameId);assert.equal(ne.side,'home');assert.equal(nyj.side,'away');
let draws=0;const ctx=createCorrelationContext(()=>{draws++;return .4});assert.equal(ctx.forGame(ne.gameId),ctx.forGame(nyj.gameId));assert.equal(ctx.size(),1);assert.ok(draws>0);
console.log('engine-tests: all checks passed');
