import {simulateLeague,simulatePlayer} from '../simulator.js';
import {applyScenarioToWeek} from '../scenarios.js';
import {createSeededRng} from '../random.js';
export const teamById=(l,id)=>l.teams.find(t=>t.id===id);
export function nextMatchup(l,id){for(const w of l.schedule)for(const [a,b] of w.matchups)if(a===id||b===id)return{week:w.week,opponentId:a===id?b:a,a,b};return null}
export const teamMean=t=>(t.lineup||[]).reduce((s,p)=>s+(p.projection||0),0);
export function scheduleStrength(l,id){const os=l.schedule.map(w=>{const m=w.matchups.find(x=>x.includes(id));return m?teamById(l,m[0]===id?m[1]:m[0]):null}).filter(Boolean);return os.reduce((s,t)=>s+teamMean(t),0)/Math.max(1,os.length)}
export function matchupAnalysis(l,id,wn,sims=5000,seed=20260923){const w=l.schedule.find(x=>x.week===wn),m=w?.matchups.find(x=>x.includes(id));if(!m)return null;const a=teamById(l,m[0]),b=teamById(l,m[1]),rng=createSeededRng(seed+wn);let aw=0,bw=0,as=0,bs=0;for(let n=0;n<sims;n++){const score=t=>(t.weeklyLineups?.[wn]||t.lineup||[]).reduce((s,p)=>s+simulatePlayer(p.projection||0,p.position,rng,p.cv),0),sa=score(a),sb=score(b);as+=sa;bs+=sb;if(sa>=sb)aw++;else bw++}return{week:wn,a,b,aWin:aw/sims,bWin:bw/sims,aAvg:as/sims,bAvg:bs/sims}}
export function simulateForced(l,forced,simulations,seed){const schedule=l.schedule.map(w=>Object.keys(forced).some(k=>k.startsWith(`${w.week}|`))?applyScenarioToWeek(w,{forcedWinners:Object.fromEntries(Object.entries(forced).filter(([k])=>k.startsWith(`${w.week}|`)).map(([k,v])=>[k.split('|')[1],v]))}):w);return simulateLeague({...l,schedule,simulations,seed})}
export function forcedScenario(l,id,winnerId,sims,seed){const n=nextMatchup(l,id);return simulateForced(l,{[`${n.week}|${n.a}:${n.b}`]:winnerId},sims,seed).find(r=>r.id===id)}
export function rootingInterests(l,id,results,sims,seed){const n=nextMatchup(l,id);if(!n)return[];const w=l.schedule.find(x=>x.week===n.week),base=results.find(r=>r.id===id);return w.matchups.filter(m=>!m.includes(id)).map(([a,b])=>{const key=`${n.week}|${a}:${b}`,ra=simulateForced(l,{[key]:a},Math.min(3000,sims),seed).find(r=>r.id===id),rb=simulateForced(l,{[key]:b},Math.min(3000,sims),seed).find(r=>r.id===id);return{a,b,da:ra.playoffProbability-base.playoffProbability,db:rb.playoffProbability-base.playoffProbability}}).sort((x,y)=>Math.max(Math.abs(y.da),Math.abs(y.db))-Math.max(Math.abs(x.da),Math.abs(x.db)))}
