import {teamById,scheduleStrength,rootingInterests} from './analysis.js';
export const pct=v=>`${((v||0)*100).toFixed(1)}%`;
export const signedPct=v=>`${(v||0)>=0?'+':''}${((v||0)*100).toFixed(1)} pts`;
export function seedBars(r){return r.seedProbability.map((p,i)=>`<div class="seed-row"><span>#${i+1}</span><div class="bar"><i style="width:${p*100}%"></i></div><strong>${pct(p)}</strong></div>`).join('')}
export function scheduleRows(l,id){return l.schedule.map(w=>{const m=w.matchups.find(x=>x.includes(id));if(!m)return'';const o=teamById(l,m[0]===id?m[1]:m[0]);return`<button class="schedule-row" data-week="${w.week}"><span>Week ${w.week}</span><strong>${o.name}</strong><em>View</em></button>`}).join('')}
export function lineupHtml(t){return(t.lineup||[]).map(p=>`<div class="player-row"><span>${p.position}</span><strong>${p.name}</strong><em>${p.projection.toFixed(1)} proj</em></div>`).join('')}
export function raceHtml(l,results){const rows=results.map(r=>({...r,sos:scheduleStrength(l,r.id)})).sort((a,b)=>b.playoffProbability-a.playoffProbability),avg=rows.reduce((s,x)=>s+x.sos,0)/rows.length;return`<div class="race-panel"><div class="eyebrow">Playoff Race</div><h3>League outlook</h3><div class="race-grid">${rows.map((x,i)=>`<div class="race-row"><b>#${i+1}</b><strong>${x.name}</strong><span>${pct(x.playoffProbability)}</span><em>${x.playoffProbability>=.995?'Near lock':x.playoffProbability<=.005?'Near elimination':i<l.playoffSpots?'In field':'Chasing'}</em><small>ROS opp avg ${x.sos.toFixed(1)} · ${x.sos-avg>1?'harder':x.sos-avg<-1?'easier':'average'}</small></div>`).join('')}</div></div>`}
export function scenarioLabHtml(l,week,forced){const w=l.schedule.find(x=>x.week===week);return`<div class="scenario-lab"><div class="eyebrow">Weekly Scenario Lab</div><h3>Set Week ${week} winners</h3><p class="lab-help">Choose winners for any games, then rerun the season. Unselected games remain simulated.</p>${w.matchups.map(([a,b])=>{const key=`${week}|${a}:${b}`,v=forced[key];return`<div class="pick-row"><span>${teamById(l,a).name}</span><button data-pick-key="${key}" data-winner="${a}" class="${v===a?'active':''}">Win</button><b>vs</b><button data-pick-key="${key}" data-winner="${b}" class="${v===b?'active':''}">Win</button><span>${teamById(l,b).name}</span></div>`}).join('')}<div class="scenario-buttons"><button data-lab="run">Run scenario</button><button data-lab="clear">Clear picks</button></div><div id="lab-result" class="scenario-result">No games forced yet.</div></div>`}
export function rootingHtml(l,id,results,sims,seed){const interests=rootingInterests(l,id,results,sims,seed);if(!interests.length)return'';return`<div class="rooting-panel"><div class="eyebrow">Rooting Interests</div><h3>Best outside results for ${teamById(l,id).name}</h3>${interests.map(x=>{const prefer=x.da>=x.db?x.a:x.b,d=x.da>=x.db?x.da:x.db;return`<div class="root-row"><span>${teamById(l,x.a).name} vs ${teamById(l,x.b).name}</span><strong>Root for ${teamById(l,prefer).name}</strong><em>${signedPct(d)}</em></div>`}).join('')}<p class="demo-disclaimer">Each game is tested independently; effects are approximate and may not add together.</p></div>`}
