const app=document.querySelector('#app'),status=document.querySelector('#status'),trust=document.querySelector('#trust');
let report=null,view='overview';
const pct=x=>`${(100*Number(x??0)).toFixed(1)}%`,num=x=>Number(x??0).toFixed(1),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(label,value,sub='')=>`<section class="card"><div class="label">${esc(label)}</div><div class="metric">${esc(value)}</div><div class="sub">${esc(sub)}</div></section>`;
function lineup(){const rows=report.roster?.starters??[];return `<section class="card full"><div class="label">Recommended / current starters</div><div class="rows">${rows.map(p=>`<div class="row"><div><strong>${esc(p.name)}</strong><div class="sub">${esc(p.position)}</div></div><div class="slot">${esc(p.slot??'START')}</div><div class="projection">${num(p.projection)} pts</div></div>`).join('')||'<p class="sub">No lineup rows available.</p>'}</div></section>`}
function actions(){const items=report.recommendations?.items??[];return `<section class="card full"><div class="label">GM recommendations</div>${items.map((a,i)=>`<div class="action"><strong>${i+1}. ${esc(a.title??a.action??a.type??'Recommended action')}</strong><div class="sub">${esc(a.summary??a.reason??a.rationale??a.description??'See recommendation data for details.')}</div></div>`).join('')||'<p class="sub">No recommended actions this week.</p>'}</section>`}
function playoff(){const seeds=report.outlook?.seedDistribution??[];return `<section class="card full"><div class="label">Seed distribution</div><div class="rows">${seeds.map(s=>`<div class="row"><div><strong>Seed ${s.seed}</strong></div><div></div><div class="projection">${pct(s.probability)}</div></div>`).join('')||'<p class="sub">No seed distribution available.</p>'}</div></section>`}
function overview(){const t=report.team,o=report.outlook,m=report.matchup??{};return `<div class="grid">${card('Record',`${t.record.wins}-${t.record.losses}${t.record.ties?`-${t.record.ties}`:''}`,`Current seed #${t.currentSeed}`)}${card('Playoff probability',pct(o.playoffProbability),`${o.simulations?.toLocaleString?.()??o.simulations??''} simulations`)}${card('Championship probability',pct(o.championshipProbability),`Average wins ${num(o.averageWins)}`)}<section class="card wide"><div class="label">This week</div><div class="metric">${pct(m.winProbability??m.teamWinProbability)}</div><div class="sub">Projected matchup win probability</div><div class="bar"><i style="width:${Math.max(0,Math.min(100,100*Number(m.winProbability??m.teamWinProbability??0)))}%"></i></div></section>${card('Recommendations',String(report.recommendations?.actionCount??0),report.recommendations?.strategy??'Weekly GM actions')}${actions()}</div>`}
function render(){if(!report)return;app.innerHTML=view==='overview'?overview():`<div class="grid">${view==='lineup'?lineup():view==='playoffs'?playoff():actions()}</div>`}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()}));
try{const response=await fetch('./data.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json();report=payload.report??payload;if(!report?.team)throw new Error('weekly report missing');status.textContent=`${report.team.record.wins}-${report.team.record.losses} · Seed #${report.team.currentSeed} · Updated ${new Date(report.generatedAt).toLocaleString()}`;const trusted=report.trust?.trusted&&!report.trust?.projections?.degraded;trust.textContent=trusted?'Trusted projections':report.trust?.trusted?'Fallback projections':'Data check required';trust.className=`pill ${trusted?'good':'warn'}`;render()}catch(error){status.textContent='Demo data has not been generated yet.';trust.textContent='Awaiting weekly report';trust.className='pill warn';app.innerHTML=`<section class="empty"><h2>Dashboard is ready.</h2><p>Generate the weekly intelligence report, then run <code>npm run demo:build</code>. The dashboard will load it automatically.</p><p class="sub">${esc(error.message)}</p></section>`}
