import {simulatePlayer} from './simulator.js';
import {mae,rmse,brier,logLoss,calibrationBins,expectedCalibrationError} from './model/metrics.js';
function quantile(values,q){if(!values.length)return null;const a=[...values].sort((x,y)=>x-y),pos=(a.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos);return a[lo]+(a[hi]-a[lo])*(pos-lo)}
function mean(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
export function evaluateForecast({projection,position,actual,draws=5000,rng=Math.random,cv=null}){const sims=Array.from({length:draws},()=>simulatePlayer(projection,position,rng,cv)),p10=quantile(sims,.10),p25=quantile(sims,.25),p50=quantile(sims,.50),p75=quantile(sims,.75),p90=quantile(sims,.90);return{projection,actual,position,simulatedMean:mean(sims),p10,p25,p50,p75,p90,absoluteError:Math.abs(projection-actual),squaredError:(projection-actual)**2,covered50:actual>=p25&&actual<=p75,covered80:actual>=p10&&actual<=p90,belowP10:actual<p10,aboveP90:actual>p90}}
export function summarizeBacktest(rows){const groups={ALL:rows};for(const r of rows)(groups[r.position]||=[]).push(r);return Object.entries(groups).map(([position,g])=>({position,n:g.length,mae:mean(g.map(x=>x.absoluteError)),rmse:Math.sqrt(mean(g.map(x=>x.squaredError))),coverage50:mean(g.map(x=>x.covered50?1:0)),coverage80:mean(g.map(x=>x.covered80?1:0)),lowTailRate:mean(g.map(x=>x.belowP10?1:0)),highTailRate:mean(g.map(x=>x.aboveP90?1:0))}))}
export function calibrationPenalty(s){return Math.abs(s.coverage50-.50)+Math.abs(s.coverage80-.80)+Math.abs(s.lowTailRate-.10)+Math.abs(s.highTailRate-.10)}
export function evaluatePointForecasts(rows){return{n:rows.length,mae:mae(rows),rmse:rmse(rows)}}
export function evaluateProbabilityForecasts(rows,{bins=10}={}){return{n:rows.length,brier:brier(rows),logLoss:logLoss(rows),ece:expectedCalibrationError(rows,bins),calibration:calibrationBins(rows,bins)}}
export function compareModels(modelRows){return Object.entries(modelRows).map(([model,rows])=>({model,...evaluatePointForecasts(rows)})).sort((a,b)=>a.rmse-b.rmse)}
