import {createDemoLeague} from './demo-data.js';
import {simulateLeague} from './simulator.js';
import {createDashboardState} from './ui/state.js';
import {nextMatchup,teamById,matchupAnalysis,simulateForced,forcedScenario} from './ui/analysis.js';
import {pct,signedPct,seedBars,scheduleRows,lineupHtml,raceHtml,scenarioLabHtml,rootingHtml} from './ui/renderers.js';
const DEFAULT_SIMULATIONS=10000,DEFAULT_SEED=20260923;
export function runDemo({simulations=DEFAULT_SIMULATIONS,seed=DEFAULT_SEED,league=createDemoLeague()}={}){return simulateLeague({...league,simulations,seed})}
export function renderDashboard(root,{simulations=DEFAULT_SIMULATIONS,seed=DEFAULT_SEED}={}){
 const league=createDemoLeague(),results=runDemo({simulations,seed,league}),store=createDashboardState(results[0].id);
 function render(){const state=store.get(),selected=state.selectedTeamId,sorted=[...results].sort((a,b)=>b.playoffProbability-a.playoffProbability),r=results.find(x=>x.id===selected),t=teamById(league,selected),n=nextMatchup(league,selected),o=n?teamById(league,n.opponentId):null;root.innerHTML=`<div class="dash-head"><div><div class="eyebrow">Synthetic Development League</div><h2>Monte Carlo Dashboard</h2></div><div class="sim-note">${simulations.toLocaleString()} simulations · seed ${seed}</div></div><div class="table-wrap"><table><thead><tr><th>Team</th><th>Avg Wins</th><th>Playoffs</th><th>#1 Seed</th><th>Champion</th></tr></thead><tbody>${sorted.map(x=>`<tr class="team-row ${x.id===selected?'selected':''}" data-team="${x.id}" tabindex="0"><td><strong>${x.name}</strong></td><td>${x.averageWins.toFixed(2)}</td><td>${pct(x.playoffProbability)}</td><td>${pct(x.seedProbability[0])}</td><td>${pct(x.championshipProbability)}</td></tr>`).join('')}</tbody></table></div><div class="detail-grid"><div class="detail-card"><div class="eyebrow">Selected Team</div><h3>${t.name} · ${t.wins}-${t.losses}</h3><div class="metric-grid"><div><span>Playoffs</span><strong>${pct(r.playoffProbability)}</strong></div><div><span>Champion</span><strong>${pct(r.championshipProbability)}</strong></div><div><span>Avg final wins</span><strong>${r.averageWins.toFixed(2)}</strong></div></div><h4>Seed distribution</h4>${seedBars(r)}</div><div class="detail-card"><div class="eyebrow">Remaining Schedule</div>${scheduleRows(league,selected)}<h4>Next matchup</h4><p>${n?`Week ${n.week} vs. <strong>${o.name}</strong>`:'Complete'}</p>${n?`<div class="scenario-buttons"><button data-scenario="win">If ${t.name} wins</button><button data-scenario="loss">If ${t.name} loses</button><button data-scenario="reset">Reset</button></div><div id="scenario-result" class="scenario-result">Choose a scenario.</div>`:''}</div></div><div id="matchup-detail"></div>${n?scenarioLabHtml(league,n.week,state.forced)+rootingHtml(league,selected,results,simulations,seed):''}${raceHtml(league,results)}<p class="demo-disclaimer">Development demo only. Synthetic teams, players and projections.</p>`;if(state.selectedWeek)renderMatchup(state.selectedWeek)}
 function renderMatchup(week){const h=root.querySelector('#matchup-detail'),m=matchupAnalysis(league,store.get().selectedTeamId,week);if(!h||!m)return;h.innerHTML=`<div class="matchup-panel"><div class="eyebrow">Week ${m.week} Matchup Analysis</div><div class="matchup-score"><div><h3>${m.a.name}</h3><strong>${m.aAvg.toFixed(1)}</strong><span>${pct(m.aWin)} win</span></div><b>VS</b><div><h3>${m.b.name}</h3><strong>${m.bAvg.toFixed(1)}</strong><span>${pct(m.bWin)} win</span></div></div><div class="lineup-grid"><div><h4>${m.a.name} lineup</h4>${lineupHtml(m.a)}</div><div><h4>${m.b.name} lineup</h4>${lineupHtml(m.b)}</div></div></div>`}
 root.onclick=e=>{const row=e.target.closest('[data-team]');if(row){store.selectTeam(row.dataset.team);return}const wk=e.target.closest('[data-week]');if(wk){store.selectWeek(wk.dataset.week);return}const pick=e.target.closest('[data-pick-key]');if(pick){store.setPick(pick.dataset.pickKey,pick.dataset.winner);return}const lab=e.target.closest('[data-lab]');if(lab){if(lab.dataset.lab==='clear'){store.clearPicks();return}const box=root.querySelector('#lab-result'),state=store.get();box.textContent='Running multi-game scenario…';setTimeout(()=>{const sr=simulateForced(league,state.forced,simulations,seed),base=results.find(r=>r.id===state.selectedTeamId),x=sr.find(r=>r.id===state.selectedTeamId);box.innerHTML=`<strong>${Object.keys(state.forced).length} forced result(s):</strong> Playoffs ${pct(x.playoffProbability)} (${signedPct(x.playoffProbability-base.playoffProbability)}), Champion ${pct(x.championshipProbability)} (${signedPct(x.championshipProbability-base.championshipProbability)}).`},20);return}const btn=e.target.closest('[data-scenario]');if(!btn)return;const box=root.querySelector('#scenario-result'),state=store.get();if(btn.dataset.scenario==='reset'){box.textContent='Choose a scenario.';return}box.textContent='Running scenario…';setTimeout(()=>{const n=nextMatchup(league,state.selectedTeamId),base=results.find(x=>x.id===state.selectedTeamId),winner=btn.dataset.scenario==='win'?state.selectedTeamId:n.opponentId,sr=forcedScenario(league,state.selectedTeamId,winner,simulations,seed);box.innerHTML=`<strong>${btn.dataset.scenario==='win'?'Win':'Loss'}:</strong> Playoffs ${pct(sr.playoffProbability)} (${signedPct(sr.playoffProbability-base.playoffProbability)}), Champion ${pct(sr.championshipProbability)} (${signedPct(sr.championshipProbability-base.championshipProbability)}).`},20)};
 root.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-team]')){e.preventDefault();store.selectTeam(e.target.dataset.team)}};store.subscribe(render);render();
}
