import { createDemoLeague } from './demo-data.js';
import { simulateLeague, simulatePlayer } from './simulator.js';
import { applyScenarioToWeek } from './scenarios.js';
import { createSeededRng } from './random.js';
const DEFAULT_SIMULATIONS=10000,DEFAULT_SEED=20260923,pct=v=>`${((v||0)*100).toFixed(1)}%`,signedPct=v=>`${(v||0)>=0?'+':''}${((v||0)*100).toFixed(1)} pts`,teamById=(l,id)=>l.teams.find(t=>t.id===id);
export function runDemo({simulations=DEFAULT_SIMULATIONS,seed=DEFAULT_SEED,league=createDemoLeague()}={}){return simulateLeague({...league,simulations,seed})}
function nextMatchup(l,id){for(const w of l.schedule)for(const [a,b] of w.matchups)if(a===id||b===id)return{week:w.week,opponentId:a===id?b:a,a,b};return null}
function seedBars(r){return r.seedProbability.map((p,i)=>`<div class="seed-row"><span>#${i+1}</span><div class="bar"><i style="width:${p*100}%"></i></div><strong>${pct(p)}</strong></div>`).join('')}
function scheduleRows(l,id){return l.schedule.map(w=>{const m=w.matchups.find(x=>x.includes(id));if(!m)return'';const o=teamById(l,m[0]===id?m[1]:m[0]);return`<button class="schedule-row" data-week="${w.week}"><span>Week ${w.week}</span><strong>${o.name}</strong><em>View</em></button>`}).join('')}
function teamMean(t){return(t.lineup||[]).reduce((s,p)=>s+(p.projection||0),0)}function scheduleStrength(l,id){const os=l.schedule.map(w=>{const m=w.matchups.find(x=>x.includes(id));return m?teamById(l,m[0]===id?m[1]:m[0]):null}).filter(Boolean);return os.reduce((s,t)=>s+teamMean(t),0)/Math.max(1,os.length)}
function matchupAnalysis(l,id,wn,sims=5000,seed=DEFAULT_SEED){const w=l.schedule.find(x=>x.week===wn),m=w?.matchups.find(x=>x.includes(id));if(!m)return null;const a=teamById(l,m[0]),b=teamById(l,m[1]),rng=createSeededRng(seed+wn);let aw=0,bw=0,as=0,bs=0;for(let n=0;n<sims;n++){const score=t=>(t.weeklyLineups?.[wn]||t.lineup||[]).reduce((s,p)=>s+simulatePlayer(p.projection||0,p.position,rng,p.cv),0),sa=score(a),sb=score(b);as+=sa;bs+=sb;if(sa>=sb)aw++;else bw++}return{week:wn,a,b,aWin:aw/sims,bWin:bw/sims,aAvg:as/sims,bAvg:bs/sims}}
function lineupHtml(t){return(t.lineup||[]).map(p=>`<div class="player-row"><span>${p.position}</span><strong>${p.name}</strong><em>${p.projection.toFixed(1)} proj</em></div>`).join('')}
function simulateForced(l,forced,simulations,seed){const schedule=l.schedule.map(w=>Object.keys(forced).some(k=>k.startsWith(`${w.week}|`))?applyScenarioToWeek(w,{forcedWinners:Object.fromEntries(Object.entries(forced).filter(([k])=>k.startsWith(`${w.week}|`)).map(([k,v])=>[k.split('|')[1],v]))}):w);return simulateLeague({...l,schedule,simulations,seed})}
function forcedScenario(l,id,winnerId,sims,seed){const n=nextMatchup(l,id);return simulateForced(l,{[`${n.week}|${n.a}:${n.b}`]:winnerId},sims,seed).find(r=>r.id===id)}
function raceHtml(l,results){const rows=results.map(r=>({...r,sos:scheduleStrength(l,r.id)})).sort((a,b)=>b.playoffProbability-a.playoffProbability),avg=rows.reduce((s,x)=>s+x.sos,0)/rows.length;return`<div class="race-panel"><div class="eyebrow">Playoff Race</div><h3>League outlook</h3><div class="race-grid">${rows.map((x,i)=>`<div class="race-row"><b>#${i+1}</b><strong>${x.name}</strong><span>${pct(x.playoffProbability)}</span><em>${x.playoffProbability>=.995?'Near lock':x.playoffProbability<=.005?'Near elimination':i<l.playoffSpots?'In field':'Chasing'}</em><small>ROS opp avg ${x.sos.toFixed(1)} · ${x.sos-avg>1?'harder':x.sos-avg<-1?'easier':'average'}</small></div>`).join('')}</div></div>`}
function scenarioLabHtml(l,id,week,forced){const w=l.schedule.find(x=>x.week===week);return`<div class="scenario-lab"><div class="eyebrow">Weekly Scenario Lab</div><h3>Set Week ${week} winners</h3><p class="lab-help">Choose winners for any games, then rerun the season. Unselected games remain simulated.</p>${w.matchups.map(([a,b])=>{const key=`${week}|${a}:${b}`,v=forced[key];return`<div class="pick-row"><span>${teamById(l,a).name}</span><button data-pick-key="${key}" data-winner="${a}" class="${v===a?'active':''}">Win</button><b>vs</b><button data-pick-key="${key}" data-winner="${b}" class="${v===b?'active':''}">Win</button><span>${teamById(l,b).name}</span></div>`}).join('')}<div class="scenario-buttons"><button data-lab="run">Run scenario</button><button data-lab="clear">Clear picks</button></div><div id="lab-result" class="scenario-result">No games forced yet.</div></div>`}
function rootingHtml(l,id,results,sims,seed){const n=nextMatchup(l,id);if(!n)return'';const w=l.schedule.find(x=>x.week===n.week),base=results.find(r=>r.id===id);const interests=w.matchups.filter(m=>!m.includes(id)).map(([a,b])=>{const key=`${n.week}|${a}:${b}`,ra=simulateForced(l,{[key]:a},Math.min(3000,sims),seed).find(r=>r.id===id),rb=simulateForced(l,{[key]:b},Math.min(3000,sims),seed).find(r=>r.id===id);return{a,b,da:ra.playoffProbability-base.playoffProbability,db:rb.playoffProbability-base.playoffProbability}}).sort((x,y)=>Math.max(Math.abs(y.da),Math.abs(y.db))-Math.max(Math.abs(x.da),Math.abs(x.db)));return`<div class="rooting-panel"><div class="eyebrow">Rooting Interests</div><h3>Best outside results for ${teamById(l,id).name}</h3>${interests.map(x=>{const prefer=x.da>=x.db?x.a:x.b,d=x.da>=x.db?x.da:x.db;return`<div class="root-row"><span>${teamById(l,x.a).name} vs ${teamById(l,x.b).name}</span><strong>Root for ${teamById(l,prefer).name}</strong><em>${signedPct(d)}</em></div>`}).join('')}<p class="demo-disclaimer">Each game is tested independently with all other games simulated. Effects are approximate and may not add together.</p></div>`}
export function renderDashboard(root,{simulations=DEFAULT_SIMULATIONS,seed=DEFAULT_SEED}={}){const league=createDemoLeague(),results=runDemo({simulations,seed,league});let selected=results[0].id,selectedWeek=null,forced={};function render(){const sorted=[...results].sort((a,b)=>b.playoffProbability-a.playoffProbability),r=results.find(x=>x.id===selected),t=teamById(league,selected),n=nextMatchup(league,selected),o=n?teamById(league,n.opponentId):null;root.innerHTML=`<div class="dash-head"><div><div class="eyebrow">Synthetic Development League</div><h2>Monte Carlo Dashboard</h2></div><div class="sim-note">${simulations.toLocaleString()} simulations · seed ${seed}</div></div><div class="table-wrap"><table><thead><tr><th>Team</th><th>Avg Wins</th><th>Playoffs</th><th>#1 Seed</th><th>Champion</th></tr></thead><tbody>${sorted.map(x=>`<tr class="team-row ${x.id===selected?'selected':''}" data-team="${x.id}" tabindex="0"><td><strong>${x.name}</strong></td><td>${x.averageWins.toFixed(2)}</td><td>${pct(x.playoffProbability)}</td><td>${pct(x.seedProbability[0])}</td><td>${pct(x.championshipProbability)}</td></tr>`).join('')}</tbody></table></div><div class="detail-grid"><div class="detail-card"><div class="eyebrow">Selected Team</div><h3>${t.name} · ${t.wins}-${t.losses}</h3><div class="metric-grid"><div><span>Playoffs</span><strong>${pct(r.playoffProbability)}</strong></div><div><span>Champion</span><strong>${pct(r.championshipProbability)}</strong></div><div><span>Avg final wins</span><strong>${r.averageWins.toFixed(2)}</strong></div></div><h4>Seed distribution</h4>${seedBars(r)}</div><div class="detail-card"><div class="eyebrow">Remaining Schedule</div>${scheduleRows(league,selected)}<h4>Next matchup</h4><p>${n?`Week ${n.week} vs. <strong>${o.name}</strong>`:'Complete'}</p>${n?`<div class="scenario-buttons"><button data-scenario="win">If ${t.name} wins</button><button data-scenario="loss">If ${t.name} loses</button><button data-scenario="reset">Reset</button></div><div id="scenario-result" class="scenario-result">Choose a scenario.</div>`:''}</div></div><div id="matchup-detail"></div>${n?scenarioLabHtml(league,selected,n.week,forced)+rootingHtml(league,selected,results,simulations,seed):''}${raceHtml(league,results)}<p class="demo-disclaimer">Development demo only. Synthetic teams, players and projections.</p>`;if(selectedWeek)renderMatchup()}
function renderMatchup(){const h=root.querySelector('#matchup-detail'),m=matchupAnalysis(league,selected,selectedWeek);if(!h||!m)return;h.innerHTML=`<div class="matchup-panel"><div class="eyebrow">Week ${m.week} Matchup Analysis</div><div class="matchup-score"><div><h3>${m.a.name}</h3><strong>${m.aAvg.toFixed(1)}</strong><span>${pct(m.aWin)} win</span></div><b>VS</b><div><h3>${m.b.name}</h3><strong>${m.bAvg.toFixed(1)}</strong><span>${pct(m.bWin)} win</span></div></div><div class="lineup-grid"><div><h4>${m.a.name} lineup</h4>${lineupHtml(m.a)}</div><div><h4>${m.b.name} lineup</h4>${lineupHtml(m.b)}</div></div></div>`}
root.onclick=e=>{const row=e.target.closest('[data-team]');if(row){selected=row.dataset.team;selectedWeek=null;forced={};render();return}const wk=e.target.closest('[data-week]');if(wk){selectedWeek=Number(wk.dataset.week);renderMatchup();return}const pick=e.target.closest('[data-pick-key]');if(pick){forced[pick.dataset.pickKey]=pick.dataset.winner;render();return}const lab=e.target.closest('[data-lab]');if(lab){if(lab.dataset.lab==='clear'){forced={};render();return}const box=root.querySelector('#lab-result');box.textContent='Running multi-game scenario…';setTimeout(()=>{const sr=simulateForced(league,forced,simulations,seed),base=results.find(r=>r.id===selected),x=sr.find(r=>r.id===selected);box.innerHTML=`<strong>${Object.keys(forced).length} forced result(s):</strong> Playoffs ${pct(x.playoffProbability)} (${signedPct(x.playoffProbability-base.playoffProbability)}), Champion ${pct(x.championshipProbability)} (${signedPct(x.championshipProbability-base.championshipProbability)}).`},20);return}const btn=e.target.closest('[data-scenario]');if(!btn)return;const box=root.querySelector('#scenario-result');if(btn.dataset.scenario==='reset'){box.textContent='Choose a scenario.';return}box.textContent='Running scenario…';setTimeout(()=>{const n=nextMatchup(league,selected),base=results.find(x=>x.id===selected),winner=btn.dataset.scenario==='win'?selected:n.opponentId,sr=forcedScenario(league,selected,winner,simulations,seed);box.innerHTML=`<strong>${btn.dataset.scenario==='win'?'Win':'Loss'}:</strong> Playoffs ${pct(sr.playoffProbability)} (${signedPct(sr.playoffProbability-base.playoffProbability)}), Champion ${pct(sr.championshipProbability)} (${signedPct(sr.championshipProbability-base.championshipProbability)}).`},20)};root.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-team]')){e.preventDefault();selected=e.target.dataset.team;selectedWeek=null;forced={};render()}};render()}
